version: '3.8'
name: ${CONTAINER_NAME}

services:
  proxichat:
    image: bgoodes/proxichat:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ${CONTAINER_NAME}
    ports:
      - "${CONTAINER_PORT}:${EXPRESS_PORT}"
    environment:
      - EXPRESS_PORT=${EXPRESS_PORT}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CA_PATH=${SSL_CA_PATH}
      - SSL_PASSPHRASE=${SSL_PASSPHRASE}