version: '3.8'
name: proxichat

services:
  proxichat:
    image: bgoodes/proxichat:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: proxichat
    ports:
      - "3000:3000"
    env_file:
      - .env