version: '3.8'
name: ${CONTAINER_NAME}

services:
  proxichat:
    image: bgoodes/proxichat:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ${CONTAINER_NAME}
    ports:
      - "${CONTAINER_PORT}:${EXPRESS_PORT}"
    volumes:
      - ${SSL_CERT_PATH:-../certs/fullchain.pem}:/etc/ssl/certs/fullchain.pem
      - ${SSL_KEY_PATH:-../certs/privkey.pem}:/etc/ssl/certs/privkey.pem
    environment:
      - EXPRESS_PORT=${EXPRESS_PORT}
      - SSL_CERT_PATH=/etc/ssl/certs/fullchain.pem
      - SSL_KEY_PATH=/etc/ssl/certs/privkey.pem
      - SSL_PASSPHRASE=${SSL_PASSPHRASE}