version: '3.8'
name: ${CONTAINER_NAME}

services:
  proxichat:
    image: bgoodes/proxichat:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ${CONTAINER_NAME}
    ports:
      - "${CONTAINER_PORT}:${EXPRESS_PORT}"
    env_file:
      - .env
    