name: ProxiChatPlugin
version: '1.0-SNAPSHOT'
main: fr.hactazia.proxichat.proxichat.ProxiChatPlugin
api-version: '1.21'
authors: [ Hactazia ]
commands:
  proxichat:
    description: Manage chat settings
    usage: /pc <help | mute | unmute | mutetoggle | link>
    aliases: [ pc ]